### PR TITLE
fixed broken links in index.jade & layout.jade

### PR DESCRIPTION
**Pull request by SHIVANGISINGH1**
I have fixed broken links in the index and layout file. 

This PR is referenced to issue [#389 ](https://github.com/publiclab/infragram/issues/389) created in the[ Publiclab/Infragram repository ](https://github.com/publiclab/infragram)

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @SHIVANGISINGH1, you pushed to your fork instead of `publiclab/infragram`.

**Comment by SHIVANGISINGH1** [comment]
> Hi @SHIVANGISINGH1, you pushed to your fork instead of `publiclab/infragram`.

I am a little confused 
I have pushed to publiclab:main from my branch 
git hub

**Comment by SHIVANGISINGH1** [comment]
> > Hi @SHIVANGISINGH1, you pushed to your fork instead of `publiclab/infragram`.
> 
> I am a little confused I have pushed to publiclab:main from my branch git hub

Hey, @TildaDares please if you could guide me on this one🙇‍♀️

**Comment by TildaDares** [comment]
Hi @SHIVANGISINGH1, this is the wrong repo. The one you need to fork is https://github.com/publiclab/infragram/.

**Comment by SHIVANGISINGH1** [comment]
> Hi @SHIVANGISINGH1, this is the wrong repo. The one you need to fork is https://github.com/publiclab/infragram/.

I have created an issue for broken links on the Infragram website main page [#389](https://github.com/publiclab/infragram/issues/389) , and I did not find the code to fix it on the https://github.com/publiclab/infragram/ . So I forked this repo instead.

**Comment by TildaDares** [comment]
This repo isn’t a part of Public Lab.

**Comment by SHIVANGISINGH1** [comment]
> This repo isn’t a part of Public Lab.

Oh so sorry, I did not know that. Should I close this pr then ?

**Comment by TildaDares** [comment]
Yeah you can close it.

**Pull request closed without merging**
